package webambulanze

/**
 * Created with IntelliJ IDEA.
 * User: Gac
 * Date: 14-1-13
 * Time: 07:56
 */
public enum Aspetto {
    titoloimmagine,
    titolocroce,
    titolologin,
    titolilegenda,
    titoligiorni,
    turnovuoto,
    turnoprevisto,
    turnoassegnato,
    turnolibero,
    turnocritico,
    turnobloccato,
    turnoeffettuato,
    turnovuotobordo,
    turnoprevistobordo,
    turnoassegnatobordo,
    turnoliberobordo,
    turnocriticobordo,
    turnobloccatobordo,
    turnoeffettuatobordo,
    turnovuotobordosup,
    turnoprevistobordosup,
    turnoassegnatobordosup,
    turnoliberobordosup,
    turnocriticobordosup,
    turnobloccatobordosup,
    turnoeffettuatobordosup,
    footercella,
    turnoorario,
    turnoorariobordo,
    legendatipo,
    legendatipoodd,
    legendatipooddbordo,
    legendatipoeven,
    legendatipoevenbordo,
    legendafunzione,
    legendaorario,
    legendaorariobordo,
    footerlegenda,
    formcaption,
    formtable,
    formlabelleft,
    formlabelright,
    formeditleft,
    formeditright,
    formlegenda,
    amb,
    copyright,
    rosso,
    verde,
    bordo
}// fine della classe Enumeration
